### ISSUE TITLE
Anyone successfully implemented?

### ISSUE THREAD

**Issue by otbox21** [archagon/tasty-imitation-keyboard#122]
Just wondering.  I've looked at this code for a day and don't really even know where to start.

(I made a keyboard app but can't stand the jumping glitch that my using storyboards caused, so I was looking for a code-only keyboard to sample)

**Comment by simoncorstonoliver** [comment]
one thing it took me a while to understand (it's been a while since I looked at the code but hope this is helpful): there are keys, skin etc then there is an invisible layer over the whole thing. When you think you're pressing a key you're actually touching this invisible layer which figures out which key you're closest to -- e.g. what should happen if you touch between the "W" and "E" keys?

But that's a wild guess at what might be confusing. Is there some specific area you don't understand?

**Comment by otbox21** [comment]
ahhhhh...that makes sense.  My confusion just comes from the fact that I'm very new to coding.  This really does work so much better than the one I built in storyboards, so I'd love to be able to implement this.  Off to my iOS Study Group to ask more questions.  Thanks!
